### ISSUE TITLE
Build failing with the following error

### ISSUE THREAD

**Issue by vamsishankar2711763** [FirmwareDroid/FirmwareDroid#197]
![image](https://github.com/user-attachments/assets/fdcf7767-c96b-4d04-bbf1-3bdb161c87c5)

**Comment by 7homasSutter** [comment]
@vamsishankar2711763 I guess to fix this issue you need to re-run the setup.py script. I added some new environment options for docker in the `.env` file so that it is possible to set limits for cpu and memory usage.
    docker_memory_limit = None
    docker_memory_swap_limit = None
    docker_cpu_limit = None
    
 Alternative you can add the following lines to the .env file to fix the issue:
 ```
 # Docker Memory
DOCKER_CPU_LIMIT=0.5
DOCKER_MEMORY_LIMIT=10GB
DOCKER_MEMORY_SWAP_LIMIT=10GB
 ```
